<?php

namespace TDengine;

const TSDB_DATA_TYPE_BINARY = 8;
const TSDB_DATA_TYPE_NULL = 0;
const TSDB_DATA_TYPE_BOOL = 1;
const TSDB_DATA_TYPE_TINYINT = 2;
const TSDB_DATA_TYPE_SMALLINT = 3;
const TSDB_DATA_TYPE_INT = 4;
const TSDB_DATA_TYPE_BIGINT = 5;
const TSDB_DATA_TYPE_FLOAT = 6;
const TSDB_DATA_TYPE_DOUBLE = 7;
const TSDB_DATA_TYPE_VARCHAR = 8;
const TSDB_DATA_TYPE_TIMESTAMP = 9;
const TSDB_DATA_TYPE_NCHAR = 10;
const TSDB_DATA_TYPE_UTINYINT = 11;
const TSDB_DATA_TYPE_USMALLINT = 12;
const TSDB_DATA_TYPE_UINT = 13;
const TSDB_DATA_TYPE_UBIGINT = 14;
const TSDB_DATA_TYPE_JSON = 15;
const TSDB_DATA_TYPE_VARBINARY = 16;
const TSDB_DATA_TYPE_DECIMAL = 17;
const TSDB_DATA_TYPE_BLOB = 18;
const TSDB_DATA_TYPE_MEDIUMBLOB = 19;
const TSDB_DATA_TYPE_GEOMETRY = 20;
const TSDB_DATA_TYPE_MAX = 21;